# Generated by Django 5.2 on 2025-07-17 16:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("Departments", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Batch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "short_name",
                    models.CharField(blank=True, max_length=5, null=True, unique=True),
                ),
                ("batch_number", models.IntegerField(verbose_name="Batch Number")),
                ("start_date", models.DateField(verbose_name="Start Date")),
                ("end_date", models.DateField(editable=False, verbose_name="End Date")),
                (
                    "total_students",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Enter the total number of students in this batch",
                        verbose_name="Total Students",
                    ),
                ),
                (
                    "department",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Departments.department",
                        verbose_name="Department",
                    ),
                ),
            ],
            options={
                "verbose_name": "Batch",
                "verbose_name_plural": "Batches",
                "ordering": ["start_date"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("department", "batch_number"),
                        name="unique_batch_per_department",
                    )
                ],
            },
        ),
    ]
