# Generated by Django 5.2 on 2025-05-22 07:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("Departments", "0005_alter_batch_unique_together_remove_batch_department"),
    ]

    operations = [
        migrations.CreateModel(
            name="Batch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("batch_number", models.IntegerField()),
                ("start_date", models.DateField()),
                ("end_date", models.DateField(editable=False)),
                ("total_students", models.IntegerField(default=0)),
                (
                    "department",
                    models.ForeignKey(
                        default=1,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Departments.department",
                        verbose_name="Department",
                    ),
                ),
            ],
            options={
                "verbose_name": "Batch",
                "verbose_name_plural": "Batches",
                "ordering": ["start_date"],
                "unique_together": {("department", "batch_number")},
            },
        ),
    ]
