# Generated by Django 5.2 on 2025-05-30 01:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Departments", "0009_department_short_name"),
        ("batch", "0001_initial"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="batch",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="batch",
            name="short_name",
            field=models.CharField(default="CSE01", max_length=5, unique=True),
        ),
        migrations.AlterField(
            model_name="batch",
            name="batch_number",
            field=models.IntegerField(verbose_name="Batch Number"),
        ),
        migrations.AlterField(
            model_name="batch",
            name="department",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="Departments.department",
                verbose_name="Department",
            ),
        ),
        migrations.AlterField(
            model_name="batch",
            name="end_date",
            field=models.DateField(editable=False, verbose_name="End Date"),
        ),
        migrations.AlterField(
            model_name="batch",
            name="start_date",
            field=models.DateField(verbose_name="Start Date"),
        ),
        migrations.AlterField(
            model_name="batch",
            name="total_students",
            field=models.PositiveIntegerField(
                default=0,
                help_text="Enter the total number of students in this batch",
                verbose_name="Total Students",
            ),
        ),
        migrations.AddConstraint(
            model_name="batch",
            constraint=models.UniqueConstraint(
                fields=("department", "batch_number"),
                name="unique_batch_per_department",
            ),
        ),
    ]
