# Generated by Django 5.2 on 2025-05-30 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("batch", "0002_alter_batch_unique_together_batch_short_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="batch",
            name="short_name",
            field=models.CharField(blank=True, max_length=5, null=True, unique=True),
        ),
    ]
