# Generated by Django 5.1.3 on 2024-12-15 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0002_departmentheadaccount'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentaccount',
            name='Class_Representetive',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='teacheraccount',
            name='Department_head',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='DepartmentHeadAccount',
        ),
    ]
