# Generated by Django 5.1.3 on 2024-12-19 16:04

import datetime

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "Accounts",
            "0004_account_email_account_first_name_account_last_name_and_more",
        ),
        ("Departments", "0003_alter_batch_end_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="studentaccount",
            name="batch",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="Departments.batch",
                verbose_name="Batch",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="account",
            name="date_of_birth",
            field=models.DateField(
                blank=True, default=datetime.date(1000, 1, 1), null=True
            ),
        ),
    ]
