# Generated by Django 5.1.4 on 2025-01-16 12:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Accounts", "0005_studentaccount_batch_alter_account_date_of_birth"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="account",
            name="email",
        ),
        migrations.RemoveField(
            model_name="account",
            name="first_name",
        ),
        migrations.RemoveField(
            model_name="account",
            name="last_name",
        ),
        migrations.RemoveField(
            model_name="account",
            name="username",
        ),
        migrations.AlterField(
            model_name="account",
            name="date_of_birth",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="account",
            name="mobile",
            field=models.CharField(
                blank=True,
                max_length=11,
                null=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Mobile number must be exactly 11 digits.",
                        regex="^\\d{11}$",
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="account",
            name="profile_picture",
            field=models.URLField(
                blank=True, default="https://i.imgur.com/"
                "placeholder.png", null=True
            ),
        ),
    ]
