# Generated by Django 5.2 on 2025-05-22 07:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Accounts", "0006_remove_account_email_remove_account_first_name_and_more"),
        ("batch", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="studentaccount",
            name="batch",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="batch.batch",
                verbose_name="Batch",
            ),
        ),
    ]
