# Generated by Django 5.2 on 2025-05-30 08:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Accounts", "0007_alter_studentaccount_batch"),
        ("Departments", "0009_department_short_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="teacheraccount",
            name="department",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="Departments.department",
                verbose_name="Department",
            ),
        ),
    ]
