# Generated by Django 5.2 on 2025-07-29 06:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="credit",
            field=models.DecimalField(
                decimal_places=2,
                help_text="Credit must be between 0.5 and 4.0",
                max_digits=4,
                validators=[
                    django.core.validators.MinValueValidator(0.5),
                    django.core.validators.MaxValueValidator(4.0),
                ],
            ),
        ),
    ]
