# Generated by Django 5.0.4 on 2024-11-18 09:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Accounts', '0002_departmentheadaccount'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('total_students', models.IntegerField()),
                ('department_head', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Accounts.departmentheadaccount', verbose_name='head')),
            ],
        ),
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_number', models.IntegerField(unique=True)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('total_students', models.IntegerField()),
                ('department_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Departments.department', verbose_name='department')),
            ],
        ),
    ]
