# Generated by Django 5.1.4 on 2025-01-18 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Departments", "0003_alter_batch_end_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="batch",
            name="total_students",
            field=models.IntegerField(default=0),
        ),
    ]
