# Generated by Django 5.2 on 2025-05-22 07:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Departments", "0004_alter_batch_total_students"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="batch",
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name="batch",
            name="department",
        ),
    ]
