# Generated by Django 5.2 on 2025-05-22 07:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Accounts", "0007_alter_studentaccount_batch"),
        ("Departments", "0005_alter_batch_unique_together_remove_batch_department"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Batch",
        ),
    ]
