# Generated by Django 5.2 on 2025-05-23 15:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Accounts", "0007_alter_studentaccount_batch"),
        ("Departments", "0006_delete_batch"),
        ("university", "0006_alter_university_starting_date_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="department",
            name="total_students",
        ),
        migrations.AlterField(
            model_name="department",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="department",
            name="department_head",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="headed_department",
                to="Accounts.teacheraccount",
                verbose_name="Department Head",
            ),
        ),
        migrations.AlterField(
            model_name="department",
            name="university",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="departments",
                to="university.university",
                verbose_name="University",
            ),
        ),
    ]
