# Generated by Django 5.2 on 2025-05-23 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Departments", "0007_remove_department_total_students_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="department",
            name="department_head",
        ),
    ]
