# Generated by Django 5.2 on 2025-05-30 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Departments", "0008_remove_department_department_head"),
    ]

    operations = [
        migrations.AddField(
            model_name="department",
            name="short_name",
            field=models.CharField(default="CSE", max_length=3, unique=True),
        ),
    ]
