# Generated by Django 5.1.3 on 2024-12-17 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("university", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="university",
            name="created_at",
            field=models.DateTimeField(),
        ),
    ]
