# Generated by Django 5.1.3 on 2024-12-19 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("university", "0002_alter_university_created_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="university",
            name="created_at",
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name="university",
            name="starting_date",
            field=models.DateField(auto_now=True),
        ),
    ]
