# Generated by Django 5.1.3 on 2024-12-19 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("university", "0003_alter_university_created_at_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="university",
            old_name="created_at",
            new_name="established_date",
        ),
    ]
