# Generated by Django 5.1.3 on 2024-12-24 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0005_alter_university_starting_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='university',
            name='starting_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='university',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
