# Generated by Django 5.2 on 2025-06-12 12:22

import common.validators.user_validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("university", "0007_alter_university_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="university",
            name="established_date",
            field=models.DateField(
                validators=[common.validators.user_validators.validate_not_future_date]
            ),
        ),
    ]
